/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActIndiaRouteImport } from './routes/act-india'
import { Route as LiraRouteImport } from './routes/lira'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActIndiaRoute = ActIndiaRouteImport.update({
  id: '/act-india',
  path: '/act-india',
  getParentRoute: () => rootRouteImport,
} as any)
const LiraRoute = LiraRouteImport.update({
  id: '/lira',
  path: '/lira',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/act-india': typeof ActIndiaRoute
  '/lira': typeof LiraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/act-india': typeof ActIndiaRoute
  '/lira': typeof LiraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/act-india': typeof ActIndiaRoute
  '/lira': typeof LiraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/act-india' | '/lira'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/act-india' | '/lira'
  id: '__root__' | '/' | '/act-india' | '/lira'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActIndiaRoute: typeof ActIndiaRoute
  LiraRoute: typeof LiraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/act-india': {
      id: '/act-india'
      path: '/act-india'
      fullPath: '/act-india'
      preLoaderRoute: typeof ActIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lira': {
      id: '/lira'
      path: '/lira'
      fullPath: '/lira'
      preLoaderRoute: typeof LiraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActIndiaRoute: ActIndiaRoute,
  LiraRoute: LiraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
